starknet-io/types-rs

.github/workflows/test.yml, crates/stark-felt/Cargo.toml, crates/stark-felt/src/lib.rs
A very preliminary API surface for the `stark-felt` crate. It's largely modeled after `starknet-ff` but also modified based on my survey of other felt impls. Obviously this would need feedback from the prominent felt users.
Once we can agree on an API surface, IMO the best way to test its fitness would be for felt dependants to actually start trying to switch to this crate to see if they can get it to compile. Obviously it would just panic at runtime but this ensures our API is good enough.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/types-rs/1)
=> feat: propose stark-felt api

README.md, crates/stark-felt/Cargo.toml, crates/stark-felt/README.md, crates/stark-felt/src/arbitrary.rs, crates/stark-felt/src/lib.rs
This PR implements the current api in the stark-felt crate using the [LambdaWorks](https://github.com/lambdaclass/lambdaworks) library
=> feat: Use `LambdaWorks`' `FieldElement` in `stark-felt` crate

.github/workflows/test.yml, Cargo.toml, crates/stark-felt/src/lib.rs, ensure_no_std/.cargo/config.toml, ensure_no_std/Cargo.toml, ensure_no_std/rust-toolchain.toml, ensure_no_std/src/main.rs, rust-toolchain.toml
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/types-rs/3)
=> ci: update ci + add ensure no std

crates/starknet-types-core/src/felt.rs
There is an error in the compilation of the Library, I think because we merged these two PRs, and we do not have a merge queue
https://github.com/starknet-io/types-rs/pull/15
https://github.com/starknet-io/types-rs/pull/16
=> Fix compilation

.github/CODEOWNERS
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
=> switch to dictatorship

crates/starknet-types-core/Cargo.toml
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
=> bump version

crates/starknet-types-core/Cargo.toml
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
=> chore: bump version for release

crates/starknet-types-core/src/hash/mod.rs, crates/starknet-types-core/src/hash/poseidon.rs
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
=> feat(hash): add poseidon hash

crates/starknet-types-core/Cargo.toml
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
=> chore: bump version

crates/starknet-types-core/src/curve/affine_point.rs, crates/starknet-types-core/src/curve/projective_point.rs, crates/starknet-types-rpc/src/lib.rs
- Feature
Add some missing operations for elliptic curve points.
- Sub operations
- Neg operations
- is_identity check
No
=> Implement some new operations for elliptic curve

crates/starknet-types-core/Cargo.toml, crates/starknet-types-core/src/felt/mod.rs
- Bump Lambdaworks version to `0.6.0`
- Use dedicated `double` function for finite field.
No
=> Bump Lambdaworks version and use double in ff

crates/starknet-types-core/Cargo.toml, rust-toolchain.toml
- Bump to last Rust stable version `1.77.0`
- Bump of various crates
No
=> Bump crates and rust version

crates/starknet-types-core/src/curve/affine_point.rs
- Feature
- Add `new_unchecked` method for `AffinePoint`
No
=> Add `new_unchecked` method for `AffinePoint`

crates/starknet-types-core/Cargo.toml
=> chore(core): bump version for release

.github/workflows/build.yml, .github/workflows/publish.yml, Cargo.toml
Publish to creates.io workflow
=> Publish to creates.io workflow

.github/CODEOWNERS
No
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/types-rs/93)
=> Update code owners: add Dan, fix Lucas

crates/starknet-types-core/Cargo.toml
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
=> bump version to 0.1.6

crates/starknet-types-core/Cargo.toml, crates/starknet-types-core/src/felt/mod.rs
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
=> Implement size_of for Felt

crates/starknet-types-core/Cargo.toml
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
=> chore: bump core version

crates/starknet-types-core/Cargo.toml, crates/starknet-types-core/src/lib.rs, crates/starknet-types-core/src/short_string/mod.rs
No breaking change.
Only add features.
closes #122
=> feat: add cairo short string logic

crates/starknet-types-core/src/hash/blake2s.rs
Refactoring (no functional changes, no API changes)
SMALL_THRESHOLD is a private const
Resolves: #NA
SMALL_THRESHOLD is public
No
needed in the blockifier, externalizing it for preventing code duplication
=> refactor: externalizing blake`s small threshold const

crates/starknet-types-core/Cargo.toml
bumping the crate`s version
No
=> bump core version
