starknet-io/types-rs

crates/starknet-types-core/Cargo.toml
crates/starknet-types-core/src/felt.rs

Reimplements the Felt methods:
* Felt::mul_mod
* Felt::mod_inverse
- Feature
No
fixes : #11

Reimplement Felt::mul_mod and Felt::mod_inverse

---

crates/starknet-types-core/Cargo.toml

No
After merging this PR it will be good to make a types-rs crate release so we can stark using types-rs in the cairo-vm #[1408](https://github.com/lambdaclass/cairo-vm/pull/1408)

Update lambdaworks version to 0.3.0

---

crates/starknet-types-core/Cargo.toml
crates/starknet-types-core/src/felt.rs

Since various crates have to work with BigInts and BigUints operations, here we implement some Felt to BigInt and Biguint conversions.
* pub fn felt_to_biguint(felt: Felt) -> BigUint
* pub fn felt_to_bigint(felt: Felt) -> BigInt
* pub fn biguint_to_felt(biguint: &BigUint) -> Felt
* pub fn bigint_to_felt(bigint: &BigInt) -> Felt
No

Implement felt to bigint functions

---

crates/starknet-types-core/Cargo.toml

The Rust standard library already requires a global allocator. This means all features that only depend on that should be usable when `std` is enabled, so let's make that implication explicit in our manifest.
- Bugfix
You need to explicitly enable `alloc` even if you're building with `std`.
Enabling `std` always enables `alloc`.
Technically, yes. You can no longer trigger a build with `std` but no global allocator. In practice, no, those builds were already broken.

fix: std requires alloc

---

crates/starknet-types-core/Cargo.toml
crates/starknet-types-core/src/felt.rs

Little helper to format felts as hex strings with prefix notation. Because the method returns a `String`, the `alloc` features is required.
- Feature
Yes

feat: hex formatting helper

---

Cargo.toml
crates/starknet-types-core/Cargo.toml

- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-

prepare publish

---

crates/starknet-types-core/Cargo.toml
crates/starknet-types-core/README.md
crates/starknet-types-core/src/felt.rs
ensure_no_std/Cargo.toml

Adds parity-scale-codec binary serialization and de-serialization for Felts under the parity-scale-codec feature flag.
- Feature
Currently, there is no support for the parity-scale-codec serialization framework. 
This PR enabled transparent support for parity-scale-codec binary  (de-)serialization of Felts when the parity-scale-codec feature flag is enabled. 
No, the parity-scale-codec flag is disabled by default.

Add parity-scale-codec serialization for Felts

---

.gitignore
crates/starknet-types-core/Cargo.toml
crates/starknet-types-core/src/felt/felt_arbitrary.rs
crates/starknet-types-core/src/felt/mod.rs
crates/starknet-types-core/src/felt/num_traits_impl.rs
crates/starknet-types-core/src/lib.rs
crates/starknet-types-rpc/Cargo.toml
ensure_no_std/Cargo.toml
ensure_no_std/src/main.rs

resolves #7 
`num_traits::{Inv, Pow, One, Zero}` are implemented on `Felt`
They exist behind a feature flag. So if you don't need them, you can build the crate without.
No

Impl num traits

---

crates/starknet-types-core/Cargo.toml
crates/starknet-types-core/src/curve/projective_point.rs

- Feature
Resolves: #NA
- Add method `ProjectivePoint::from_affine`
- Add method `ProjectivePoint.double`
No

Add methods `from_affine` & `double` to `ProjectivePoint`

---

crates/starknet-types-core/proptest-regressions/felt/mod.txt
crates/starknet-types-core/src/felt/mod.rs

- Feature
Add double implementation for Felt
- This pull request introduces a utility method `double` for the `Felt` type. The `double` method allows for more convenient and concise code when needing to double a `Felt` value. Previously, one would have to write `x + x` to achieve the same result, which can be verbose and less readable. With the addition of `double`, users can now simply call `x.double()` to achieve the same outcome.
No

Add double implementation for Felt

---

crates/starknet-types-core/src/curve/projective_point.rs

- Feature
Missing addition of projective points with affine points.
This pull request introduces the implementation for addition between projective and affine points . This implementation ensures compatibility and efficiency when performing arithmetic addition operations on points represented in different coordinate systems.
No

Implement addition between projective and affine points

---

crates/starknet-types-core/src/curve/projective_point.rs

- Testing
At the moment only the multiplication of a projective point by a u32 was tested.
This PR brings a new unit test with the multiplication of a projective point by a Felt to test the proper behavior of this operation.
No

Add unit test for Projective point scalar multiplication by Felt

---

crates/starknet-types-core/Cargo.toml
crates/starknet-types-core/src/hash/pedersen.rs

Pedersen hasher creation is slow and not needed to be done at every call of the `hash` function so put that in a const to improve the performances.

perf(hash): create pedersen hasher in a const

---

crates/starknet-types-core/Cargo.toml
crates/starknet-types-core/Makefile
crates/starknet-types-core/benches/criterion_pedersen.rs
ensure_no_std/rust-toolchain.toml
rust-toolchain.toml

* Add a criterion benchmark that runs the Pedesen::Hash function
* Add a little Makefile to the starknet-core-types crate
* Update Rust toolchain to 1.74.0 in `starknet-types-core` and `ensure_no_std` crates
No

Add Pedersen benchmark

---

crates/starknet-types-core/Cargo.toml
crates/starknet-types-core/src/hash/pedersen.rs

Updates lambdaworks to 0.6.0 to be able to use the optimized Pedersen hash.
This includes a compile-time optimization to reduce the time used to initialize the hash, and arithmetic optimizations to reduce the time of the hash itself.
NO ❌ 
Merge after the benchmarks PR #48

perf: update lambdaworks to 0.6.0

---

crates/starknet-types-core/Cargo.toml
crates/starknet-types-core/src/felt/mod.rs

lazy_static depends on spin which breaks for `thumbv6m-none-eabi` target (which is in the starknet rs ci) so put that behind a feature flag. THIS IS A BREAKING CHANGE

fix!(core): lazy_static in feature

---

crates/starknet-types-core/src/curve/projective_point.rs

- Feature
This pull request adds the implementation of the `TryFrom<AffinePoint>` trait for the `ProjectivePoint` type. This implementation allows converting an `AffinePoint` to a `ProjectivePoint` if possible, or returning an error if the conversion is not valid according to the elliptic curve arithmetic.

Implement `TryFrom<AffinePoint>` for `ProjectivePoint`

---

crates/starknet-types-core/src/hash/poseidon.rs

- Feature
Implements method `hades_permutation` for `Poseidon` struct
No
This change is needed to use this library's poseidon hash in `cairo-vm`'s `PoseidonBuiltinRunner` as it uses the internal permutation function as opossed to using `hash_many`. ([current usage](https://github.com/lambdaclass/cairo-vm/blob/95d2c88fcd4ef799ff64fc392efd633c05fa37e4/vm/src/vm/runners/builtin_runner/poseidon.rs#L96))

feat: Add `Podeidon::hades_permutation`

---

README.md

The links to `docs.rs` & `crates.io` in the README point to the old `stark-felt` crate instead of `starknet-core-types`, making it confusing for potential users
- The docs.rs & crates.io links now point to the `starknet-core-types` crate
- Mentions of the old `stark-felt` crate were removed from the README
No
I wasn't able to find `starknet-types-rpc` in crates.io

Update `docs.rs` & `crates.io` links + Remove mentions of old `stark-felt` crate

---

crates/starknet-types-core/Cargo.toml
crates/starknet-types-core/src/felt/mod.rs
ensure_no_std/rust-toolchain.toml
rust-toolchain.toml

- Bugfix
- `to_bits_le` and `to_bits_be` implementations are modified to take into account existing Lambdaworks implementation:
https://github.com/lambdaclass/lambdaworks/blob/1a6d14ee7def60d0692d2b8fd323ca0d494920fd/math/src/field/fields/fft_friendly/stark_252_prime_field.rs#L50-L67
- Unit tests are modified accordingly
- `bitvec` dependency is removed
No

Modify `to_bits` implementations

---

crates/starknet-types-core/Cargo.toml

This version contains a huge update on Poseidon benchmarks ~%60
MAC os benchmarks
```
Benchmarking Poseidon/hash: Collecting 100 samples in estimated 5.0102 s (869k i
Poseidon/hash           time:   [5.6525 µs 5.6551 µs 5.6581 µs]
change: [-63.869% -63.775% -63.692%] (p = 0.00 < 0.05)
Performance has improved.
Found 21 outliers among 100 measurements (21.00%)
12 (12.00%) low severe
3 (3.00%) high mild
6 (6.00%) high severe
Benchmarking Poseidon/hash_array/10: Collecting 100 samples in estimated 5.1021
Poseidon/hash_array/10  time:   [33.109 µs 33.264 µs 33.460 µs]
change: [-64.473% -64.321% -64.164%] (p = 0.00 < 0.05)
Performance has improved.
Benchmarking Poseidon/hash_array/100: Collecting 100 samples in estimated 5.8695
Poseidon/hash_array/100 time:   [279.14 µs 279.66 µs 280.33 µs] …
```

Update lambdaworks to 0.7.0 

---

crates/starknet-types-core/src/felt/mod.rs

- Bugfix
Hex formatting of `Felt` ignores `alternate` and zero padding options.
Hex formatting respects these options.
Technically, yes. This fix adds a requirement of `alloc` to the implementation of `LowerHex`. In reality though this will likely not affect anyone.
This is blocking https://github.com/xJonathanLEI/starknet-rs/pull/562.

fix: `Felt` hex formatting options

---

crates/starknet-types-core/src/felt/mod.rs

Building: instead of using the default macro that implements debug,
impl debug trait as a fix len hex string.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/types-rs/72)

build: impl debug for felt

---

crates/starknet-types-core/src/felt/mod.rs

- Bugfix
- Feature
- Testing
Resolves: #NA
Can easily call `FromStr::from_str` on either hex or dec string without having to do so manually.
No

Implement `FromStr` trait for `Felt`

---

.github/workflows/build.yml
crates/starknet-types-core/Cargo.toml
crates/starknet-types-core/src/felt/mod.rs

The `ftm::Debug` impl fails to compile unless the `alloc` feature is on. The underlying math lib allows `alloc`-free hex output, except it's not fixed-width like the current impl does.
This technically changes the debug output format, but it should be worth it for getting to avoid requiring `alloc` for just debug printing.
Also adds a GitHub Actions workflow to check that all feature combinations would compile correctly so that this doesn't happen again.

fix: `ftm::Debug` impl fails to compile

---

crates/starknet-types-core/src/felt/mod.rs

`Felt` supports both human readable and binary serialization, but the binary deserializer was missing. 
Yes, but likely no-one is affected by it as deserialization was not working. The (de)serialization is done with bytes rather than sequences. 
The serialization and deserialization test have been combined.  Serialization and deserialization should not be tested separately as that makes it too easy to miss a case.

Bugfix: binary deserialization `Felt`

---

.github/workflows/publish.yml
crates/starknet-types-core/Cargo.toml
crates/starknet-types-core/src/felt/mod.rs
crates/starknet-types-core/src/felt/primitive_conversions.rs
fuzz/felt/Cargo.toml
fuzz/felt/fuzz_targets/conversions.rs
rust-toolchain.toml

Update lambdaworks deps to 0.10.0 version
No

Update lambdaworks deps to 0.10.0 version

---

crates/starknet-types-core/src/felt/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/types-rs/94)

chore: code dedup in felt from bigint

---

crates/starknet-types-core/Cargo.toml

- Feature
Addition or multiplication not allowed for AffinePoint
AffinePoints could now be added or multiplied by a scalar, similar with ProjectivePoint
No
his is a new updated PR that was recently closed https://github.com/starknet-io/types-rs/pull/112

Implement multiplication and addition operations for AffinePoint

---

crates/starknet-types-core/src/felt/mod.rs

`<Felt as Arbitrary>::size_hint` returns `0`
Correctly returns the amount of bytes to construct a `Felt`.

Add `Arbitrary` size hint

---

crates/starknet-types-core/Cargo.toml
crates/starknet-types-core/src/felt/mod.rs

Reverts #123
`size-of` crate is unmaintained and doesn't compile on architectures other than `x86` when Rust version is `>1.89`.
See the [issue in `size-of`](https://github.com/Kixiron/size-of/issues/6) and [explanation of the error in Rust compiler](https://github.com/rust-lang/rust/issues/87678).
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
Theoretically, this is a breaking change. However, no crate actually uses the implementation of `SizeOf`, so in practice it isn't.

Remove `SizeOf` implementation for `Felt`

---

crates/starknet-types-core/Cargo.toml
crates/starknet-types-core/src/felt/mod.rs
crates/starknet-types-core/src/lib.rs
crates/starknet-types-core/src/u256/mod.rs
crates/starknet-types-core/src/u256/num_traits_impl.rs
crates/starknet-types-core/src/u256/primitive_conversions.rs
crates/starknet-types-core/src/u256/tests/from_dec_str.rs
crates/starknet-types-core/src/u256/tests/from_hex_str.rs
crates/starknet-types-core/src/u256/tests/mod.rs

Add a U256 type, following its cairo representation as two u128 (high and low), along with some utility functions to build those, usefull traits impl.
This struct purpose is not to do any arithmetic on u256. For this, you should convert it to your own mathematically equipped u256 type. 
It acts more as a useful intermediate representation for any display, serialization, or parsing work of cairo-represented u256 you may have to do.
No.
Should I implement From/Into logic in regard to the major u256 types here (from crates primitive-types, uint, ...)?

feat: add a u256 type

---

crates/starknet-types-core/src/felt/mod.rs

Refactoring
Currently, string-formatting a field element is implemented manually; local benchmarks indicates conversion to `BigUint` and formatting the converted element is faster.
Resolves: #NA
Refactor `Display` impl of `Felt`
No

refactor: impl Display for Felt via BigUint

---

crates/starknet-types-core/src/felt/alloc_impls.rs

Fixes #124 
The following (valid) format pattern causes a panic.
```rust
let x = Felt::from_hex_unchecked("0x4718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d");
println!("{:#0x}", x);
```
This is due to a homemade, incomplete implementation of the rust [formatting specs](https://doc.rust-lang.org/std/fmt/#sign0).
We don't panic.
We follow the specs (space padding, 0 padding).
Yes. Maximum width was previously constrained to 66. Giving a bigger value would still result in a 66 chars len string.
This constraint is now raised.
Space padding was ignored ( `println!("{:5x}", Felt::ONE);` resulted in `1` instead of `    1`). It is now working.
The new impl leverages the Rust standard library methods already available for formatting.

fix(felt): full `fmt` specs implem

---

crates/starknet-types-core/Cargo.toml
crates/starknet-types-core/src/felt/serde.rs

When serialized in a non-human-readable format, the full 32 bytes of the felt are serialized, which means the value `zero` is represented as its len `32` followed by  32 `0`. Which means 33 byte.ss in total. This is a huge waste of space and bandwidth.
- all leading zeros are ignored. `Felt::ZERO` becomes `&[1, 0]` ([len, value]), 2 bytes
YES. 
Values are serialized in the different way.
But possible bugs are mitigated by the fact that the deserialization of values is backward compatible: values serialized using the previous implementation can still be deserialized using the current one.
This means if you stored a serialized value somewhere (db, file) or if you are interacting with a service that has not updated to the new implementation, no bug will occur if you just do …

feat: improve non-human-readable felt serialization space efficiency

---

crates/starknet-types-core/src/qm31/mod.rs

We were using `to_raw` to obtain the QM31 coefficients, instead of `representative`. Internally, there are two valid representation for the zero value: `0` and `PRIME`. When packing a QM31 into a felt, however, we need to use the representative value (`0`).
- Bugfix
We are serializing a `PRIME` coefficient with the raw value (PRIME), instead of the representative value (0).
Serialize a `PRIME` coefficient with the representative value (0).
No

Fix QM31 to not use raw internal value

---

crates/starknet-types-core/Cargo.toml
crates/starknet-types-core/src/curve/affine_point.rs
crates/starknet-types-core/src/curve/projective_point.rs
crates/starknet-types-core/src/felt/mod.rs
ensure_no_std/rust-toolchain.toml
rust-toolchain.toml

Clone of #166 but it targets v0.2 instead of v0.3.
**NOTE:** This is breaking since this PR changes minimum Rust version from 1.84.1 to 1.87.0.

[v0.2] Bump Lambdaworks to 0.13.0

---

crates/starknet-types-core/src/curve/affine_point.rs
crates/starknet-types-core/src/felt/mod.rs
crates/starknet-types-core/src/felt/non_zero.rs
crates/starknet-types-core/src/felt/secret_felt.rs
crates/starknet-types-core/src/felt/serde.rs
crates/starknet-types-core/src/hash/blake2s.rs
crates/starknet-types-core/src/short_string/mod.rs
fuzz/felt/fuzz_targets/conversions.rs

`from_hex_unchecked` is badly named.
It actually checks the felt value and will panic if it is too big.
So `from_hex_unwrap` is a better name.
This PR deprecates `from_hex_unchecked` and introduces the new `from_hex_unwrap`, allowing for a non-breaking, smooth transition downstream.

chore(felt): rename from_hex_unchecked to from_hex_unwrap

---

crates/starknet-types-core/src/u256/mod.rs

- Typo in error message: `represenation` instead of `representation`
- Typo in code comment: `Intead` instead of `Instead`

fix: correct typos in u256 module documentation and error messages

---

crates/starknet-types-core/Cargo.toml
crates/starknet-types-core/src/felt/mod.rs

Patch: restore `SizeOf` for `Felt` (temporarily)
- Feature
- Other: bump patch version
No implementation of `size_of::SizeOf` on Felt since https://github.com/starknet-io/types-rs/pull/158; revert this change to publish v0.2.3, and then revert and publish 0.2.4
Resolves: lack of `SizeOf` impl
- Implementation of `SizeOf` for `Felt` is restored
- Crate patch version is bumped
Will break conflicting implementations of a `SizeOf` trait, if they exist

Restore sizeof and bump patch version to 0.2.3

---

crates/starknet-types-core/Cargo.toml
crates/starknet-types-core/src/felt/mod.rs

See [PR #172](https://github.com/starknet-io/types-rs/pull/172) - this PR reverts it, and bumps the patch version to 0.2.4

revert sizeof, bump to 0.2.4
